# Project Overview {-#overview}

## Motivation {-#motivation}

Modelling soil erosion in post-burn areas is critical for understanding how broad-scale change impacts soil properties and structures. The RUSLE, the most commonly used soil erosion model, has primarily been applied to model soil erosion in agricultural regions. Applying the RUSLE in non-agriculture regions presents a substantial challenge. This challenge is driven by data availability and the applicability of RUSLE factors for non-uniform slopes and cover classes. As a result, RUSLE outcome values for non-linear, semi-natural, or steep regions must be considered the spatial representation of trends in soil erosion. In this report, we demonstrate the application of the RUSLE for modelling soil erosion across two watersheds in the Kootenay region of British Columbia. The RUSLE soil erosion maps demonstrate the spatial variation of soil erosion across the study area and signify areas where soil erosion is predicted to be higher or lower.


## Objective {-#objective}

This project aims to apply the Revised Universal Soil Loss Equation (RUSLE) for post-fire soil erosion modelling in a study area in the West Kootenay region of southeastern British Columbia. The specific objectives of this work are to (i) collect and process soil erosion modelling data (rainfall, soil erodibility, slope length, crop cover, and management practices), (ii) apply the RUSLE across the study area, and (iii) simulate RUSLE modelling under variable fire extent conditions. This report intends to demonstrate the application of the RUSLE across a heterogeneous landscape and provide guidelines for future soil erosion modelling.

## Background {-#background}

Soil erosion involves multiple processes which collectively impact the transportation of particles across landscapes. Assessing and mitigating soil erosion and land degradation is critical due to the possible effects of these processes, which include nutrient loss, river and reservoir siltation, water quality degradation, and decreases in soil productivity ([Bagherzadeh, 2014](https://www.researchgate.net/publication/257785877_Estimation_of_soil_losses_by_USLE_model_using_GIS_at_Mashhad_plain_Northeast_of_Iran)). Across a landscape, erosion can result from flow, occur within channels of concentrated flow (rills and gullies), and occur through raindrop impact and overland flow ([Aksoy and Kavvas, 2005](https://www.researchgate.net/publication/223520981_A_review_of_hillslope_and_watershed_scale_erosion_and_sediment_transport_models)).

Wildfires are identified as one of the main drivers of soil erosion and land degradation ([Shakesby and Doerr, 2006](https://www.sciencedirect.com/science/article/pii/S0012825205001467)). One direct effect of wildfires is the loss of protective cover, which reduces rainfall interception, surface roughness, evapotranspiration, and the infiltration capacity of soils. Soil structure can be altered directly in moderate to high-severity wildfires due to the destruction of the organic or mineralogical bindings of soil particles ([Larsen and MacDonald, 2007](https://acsess.onlinelibrary.wiley.com/doi/abs/10.2136/sssaj2007.0432); [Fernández et al., 2010](https://www.researchgate.net/publication/284913901_Modelling_the_Effect_of_Soil_Burn_Severity_on_Soil_Erosion_at_Hillslope_Scale_in_the_First_Year_Following_Wildfire_in_nw_Spain)). After fires, the fraction of bare soil exposed to raindrop impact is increased, allowing the kinetic energy of raindrops to be directly transferred to the soil surface, where to soil structure is degraded ([DeBano et al., 1998](http://www.fsl.orst.edu/ltep/Biscuit/Biscuit_files/Refs/DeBano%20JH2000b%20fire.pdf); [Robichaud et al., 2000](https://www.researchgate.net/publication/222698132_Fire_Effects_on_Infiltration_Rates_After_Prescribed_Fire_in_Northern_Rocky_Mountain_Forests_USA)). The destruction of soil structure, both directly and indirectly by fire, contributes to runoff and particle detachment, and increases sediment loss ([Shakesby and Doerr, 2006](https://www.sciencedirect.com/science/article/pii/S0012825205001467)). In some conditions, the removal of the surface cover, combined with fire-induced changes, leads to the creation of soil crusts, which inhibit infiltration ([Silva et al., 2019](https://www.sciencedirect.com/science/article/pii/S0925857418304713)).

Effective land management in post-fire regions can mitigate soil erosion and limit soil degradation; such efforts can be improved by understanding how erosion processes occur and what areas are vulnerable to soil loss. Methods for estimating the risk of soil erosion are essential for planning post-fire soil management measures ([Vega et al., 2013](https://www.jstor.org/stable/42952602)). Advances in technology, such as the development of soil erosion models and increases in computing power for spatial analysis, have assisted in making soil erosion modelling faster and more accurate. The most widely used models to estimate post-fire soil erosion by water are empirically based. These include the Universal Soil Loss Equation (USLE; [Wischmeier and Smith, 1978](https://naldc.nal.usda.gov/download/CAT79706928/PDF)) and its revised form RUSLE ([Renard et al., 1997](https://www.ars.usda.gov/ARSUserFiles/64080530/RUSLE/AH_703.pdf)). The wide application of the USLE and the RUSLE is related to the fact that empirical models require less input data than physically based ones ([Merrit et al., 2003](https://www.researchgate.net/publication/228552294_A_Review_of_Erosion_and_Sediment_Transport_Models)). The USLE and RUSLE models, were developed to estimate soil erosion by water in agricultural regions and are not commonly applied for erosion modeling across rugged or burned areas with heterogenous vegetation cover ([Morrison and Kolden, 2015](https://www.researchgate.net/publication/270163637_Modeling_the_impacts_of_wildfire_on_runoff_and_pollutant_transport_from_coastal_watersheds_to_the_nearshore_environment); [Hosseini et al., 2018](https://www.mdpi.com/2073-4441/12/7/1995/htm)) and soil properties ([Chen et al., 2013](https://www.sciencedirect.com/science/article/pii/S2666683921000365); [Moody et al., 2013](https://www.researchgate.net/publication/307181869_Synthesis_of_soil-hydraulic_properties_and_infiltration_timescales_in_wildfire-affected_soils_Synthesis_of_soil-hydraulic_properties_in_wildfire-affected_soils); [Fernández and Vega, 2018](https://www.sciencedirect.com/science/article/pii/S0013935117317644); [Nunes et al., 2020](https://www.sciencedirect.com/science/article/pii/S0016706119329052)).

Post-fire soil erosion modelling can provide accurate predictions of the hydrological and geomorphological effects of fires across variable landscapes. However, building a input data database is difficult, not only because of regional differences in climate, soil properties, and fire characteristics but also due to differences in research approaches and scales ([Shakesby and Doerr, 2006](https://www.sciencedirect.com/science/article/pii/S0012825205001467)), or due to the model limitations in representing soil erosion processes ([Nearing, 1998](https://www.researchgate.net/publication/222472796_Why_Soil_Erosion_Models_Over-Predict_Small_Soil_Losses_and_Under-Predict_Large_Soil_Losses)).The need to adapt models to post-fire conditions and validate their predictions has been emphasized in several studies ([Larsen and MacDonald, 2007](https://acsess.onlinelibrary.wiley.com/doi/abs/10.2136/sssaj2007.0432); [Fernández and Vega, 2018](https://www.sciencedirect.com/science/article/pii/S0013935117317644); [Girona-García et al.,2021](https://www.sciencedirect.com/science/article/pii/S0012825221001112)), and identified as equally important to developing a new model specifically for post-fire conditions.

The integration of existing soil erosion models, field data, and data provided by remote sensing technologies through the use of geographic information systems (GIS) is an asset to post-fire soil erosion studies ([Gitas et al., 2009](https://www.researchgate.net/publication/242519680_Multi-temporal_soil_erosion_risk_assessment_in_N_Chalkidiki_using_a_modified_USLE_raster_model)). Remote sensing, which enables the modelling of long- and short-term variation in soil erosion, is a valuable tool for quantifying spatial patterns of soil erosion and land degradation over time ([Ganasri et al., 2016](https://www.sciencedirect.com/science/article/pii/S1674987115001255#!)). The increased availability of remote sensing data ([Wulder & Coops, 2014](https://www.nature.com/articles/513030a)) and ongoing computational advancements ([Azzari & Lobell, 2017](https://www.researchgate.net/publication/312518132_Satellite_detection_of_rising_maize_yield_heterogeneity_in_the_US_Midwest)) have facilitated broad-scale soil erosion research ([North et al., 2022](https://www.sciencedirect.com/science/article/pii/S0301479721018740), [Prasad et al., 2022](https://www.tandfonline.com/doi/abs/10.1080/09715010.2020.1814881)). Developing semi-automated soil erosion modelling methods using common coding languages, such as R, and GIS programs, such as ArcGIS, facilitate the development of consistent, and comparable modelling methods.

## Limitations {-#limitations}

Despite the many strengths of the RUSLE, it has limitations such that it does not capture gullying and/or shallow landslides, is not process-based, does not capture feedbacks between model components, nor does it estimate delivery/deposition of eroded sediments. Being an empirical model developed in North America for agriculture, RUSLE applications should be validated and/or calibrated when estimating surface erosion. Previous reviews have covered these limitations in detail ([Alewell et al., 2019](https://www.sciencedirect.com/science/article/pii/S2095633919300048)) and further demonstrated that RUSLE outputs have similar ranges of uncertainty when compared with more complex process-based physical models such as WEPP and PESERA. In most cases, there remain large uncertainties associated with the predictions made by models ([Batista et al. 2019](https://www.researchgate.net/publication/334496630_On_the_evaluation_of_soil_erosion_models_Are_we_doing_enough); [Baartman et al. 2020](https://www.sciencedirect.com/science/article/pii/S0169555X20302725)), particularly for those concerned with routing sediment through large and/or complex watersheds.

The RUSLE erodibility factor (K) has been the main target of criticism from several researchers. [Larsen and MacDonald (2007)](https://acsess.onlinelibrary.wiley.com/doi/abs/10.2136/sssaj2007.0432) and [Moffet et al. (2007)](https://www.researchgate.net/publication/222540666_Modeling_soil_erosion_on_steep_sagebrush_rangeland_before_and_after_prescribed_fire) suggested that the current algorithms for calculating soil erodibility are not consistent with the understanding of post-fire erosion processes. Fernández and Vega (2018) also concluded that the erodibility in the RUSLE equation does not reflect fire-induced changes in soil properties because it does not consider the influence of burn severity; while others state that the K factor does not reflect the changes in soil permeability and structure after wildfire ([Moody et al., 2013](https://onlinelibrary.wiley.com/doi/10.1002/hyp.13543); [Morrison and Kolden, 2015](https://www.researchgate.net/publication/270163637_Modeling_the_impacts_of_wildfire_on_runoff_and_pollutant_transport_from_coastal_watersheds_to_the_nearshore_environment)). [Larsen and MacDonald (2007)](https://acsess.onlinelibrary.wiley.com/doi/abs/10.2136/sssaj2007.0432) and [Moffet et al. (2007)](https://www.researchgate.net/publication/222540666_Modeling_soil_erosion_on_steep_sagebrush_rangeland_before_and_after_prescribed_fire)) also suggested that, to achieve greater precision, the K factor should be reformulated and [Larsen and MacDonald (2007)](https://acsess.onlinelibrary.wiley.com/doi/abs/10.2136/sssaj2007.0432) also suggested that soil moisture would be more properly included in the K factor, followed by an adaptation to site-specific conditions.

Several authors adapted the rainfall erosivity to local climates. However, this raised criticism of the application of the RUSLE model in recently burned areas. For example, [Larsen and MacDonald (2007)](https://acsess.onlinelibrary.wiley.com/doi/abs/10.2136/sssaj2007.0432) suggested that the R calculated according to [Wischmeier and Smith, 1978](https://naldc.nal.usda.gov/download/CAT79706928/PDF) equation would overestimate predictions due to the assumed linearity between the rainfall erosivity and sediment yields. In contrast, the same authors also suggested that if the rainfall erosivity factor is adapted to different climates, it may lead to a lower final value for the predicted soil erosion by water, with inherent implications for model performance. This study aims to produce an overview of soil erosion in the study area, which reflect the general erosion rates rather than specific per ha values. Our approach reflects the limitations of the RUSLE for post-burn areas. [Fernández and Vega, (2018)](https://www.sciencedirect.com/science/article/pii/S0013935117317644) also concluded that the soil erodibility (K) in the RUSLE equation does not reflect fire-induced changes in soil properties because it does not consider the influence of burn severity; while others state that the K factor does not reflect the changes in soil permeability and structure after fire ([Moody et al., 2013](https://onlinelibrary.wiley.com/doi/10.1002/hyp.13543); [Morrison and Kolden, 2015](https://www.researchgate.net/publication/270163637_Modeling_the_impacts_of_wildfire_on_runoff_and_pollutant_transport_from_coastal_watersheds_to_the_nearshore_environment)).
